repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--line-length=120]
        files: ^(rust_patch_monitor\.py|test_.*\.py)$

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --extend-ignore=E203,W503]
        files: ^(rust_patch_monitor\.py|test_.*\.py)$

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -m pytest test_rust_patch_monitor.py test_golden_masters.py -v
        language: system
        pass_filenames: false
        always_run: true